services:
  postgres:
    image: postgres:14.2
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      app-network:

  survey-service:
    build: .
    ports:
      - "8000:8000"
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    env_file:
      - .env
    networks:
      app-network:
    volumes:
      - ./:/app
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pg-data:
    driver: local

networks:
  app-network: